pipeline {
    agent any

    options {
        timeout(time: 9, unit: 'HOURS')   // timeout on whole pipeline job
    }
 tools {
        
        maven "MavenSystem"
    }
    stages {
        stage('Run Test') {
            steps {
                // Change directory and run Maven on a windows agent.
                bat '''
                    cd SeleniumAutomation/selenium
                    mvn clean install
                '''
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('Test_Sonar') {
                    bat '''
                        cd SeleniumAutomation/selenium
                        mvn sonar:sonar
                    '''
                }
            }
        }
         stage('Publish to artifactory') {
            steps {
                rtMavenDeployer(
                    id:'deployer',
                    serverId:'vikasjfrogart',
                    releaseRepo:'samplerepo',
                    snapshotRepo:'samplerepo'
                    )
                    rtMavenRun(
                        pom:'SeleniumAutomation/selenium/pom.xml',
                        goals:'clean install',
                        deployerId:'deployer'
                        )
                        rtPublishBuildInfo(
                            serverId:'vikasjfrogart'
                            )
               
            }
        }

    }

    post {
        
        always {
            script {
                if (currentBuild.result == 'UNSTABLE') {
                    currentBuild.result = 'FAILURE'
                }
            }
           
        }
    }
}
